const ActionTypes = {
  INCREMENT: 'INCREMENT',

  // ------------Complete User------------
  COMPLETE_USER_ACTION: 'COMPLETE_USER_ACTION',
  COMPLETE_USER_PENDING_ACTION: 'COMPLETE_USER_PENDING_ACTION',
  COMPLETE_USER_ERROR_ACTION: 'COMPLETE_USER_ERROR_ACTION',
  COMPLETE_USER_SUCCESS_ACTION: 'COMPLETE_USER_SUCCESS_ACTION',
}

export default ActionTypes
