const ActionTypes = {
  INCREMENT: 'INCREMENT',

  // ------------Complete User------------
  COMPLETE_USER_PENDING_ACTION: 'COMPLETE_USER_PENDING_ACTION',
  COMPLETE_USER_ERROR_ACTION: 'COMPLETE_USER_ERROR_ACTION',
  COMPLETE_USER_SUCCESS_ACTION: 'COMPLETE_USER_SUCCESS_ACTION',

  // ------------Delete User------------
  DELETE_USER_PENDING_ACTION: 'DELETE_USER_PENDING_ACTION',
  DELETE_USER_ERROR_ACTION: 'DELETE_USER_ERROR_ACTION',
  DELETE_USER_SUCCESS_ACTION: 'DELETE_USER_SUCCESS_ACTION',

  // ------------Edit User------------
  EDIT_USER_PENDING_ACTION: 'EDIT_USER_PENDING_ACTION',
  EDIT_USER_ERROR_ACTION: 'EDIT_USER_ERROR_ACTION',
  EDIT_USER_SUCCESS_ACTION: 'EDIT_USER_SUCCESS_ACTION',
}

export default ActionTypes
